### ISSUE TITLE
ace-container本地启动不了

### ISSUE THREAD

**Issue by gshine** [AliCloudEngine/doc#8]
win7 64位  本地启动不了

报以下两个错误：

1）找不到root.war。

```bash
2014-04-01 13:58:19,048ERROR[org.apache.catalina.startup.ContextConfig]Exception
 fixing docBase for context []
java.io.FileNotFoundException: D:\ace-container\webapps\ROOT.war (系统找不到指定
的文件。)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:127)
        at java.util.jar.JarFile.<init>(JarFile.java:136)
        at java.util.jar.JarFile.<init>(JarFile.java:73)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:72)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:48)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:80)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.ja
va:104)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection
```

2）Service config properties D:\ace-container\conf\custom\ace4j-private.properties
does not exist!

```bash
2014-04-01 13:58:20,938ERROR[com.aliyun.ace4j.container.tomcat7.AceCdnFilter]===
===> ace4j-private.properties not exits
```

**Comment by gshine** [comment]
the ace has been shut down. so this issue is meaningless.
close it.
